"""add_rerank_provider_to_assistant

Revision ID: 0083dbd5d1f2
Revises: 58d6cc79c92d
Create Date: 2026-02-14 15:16:08.981622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0083dbd5d1f2'
down_revision: Union[str, Sequence[str], None] = '58d6cc79c92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('rerank_provider', sa.Text(), server_default=sa.text("'cohere'"), nullable=False))
    op.alter_column('assistants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('chat_history_assistant_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'assistants', ['assistant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('connectors', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('connectors', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('connectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_status'), table_name='connectors')
    op.alter_column('connectors_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of creation',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Notification category or severity level',
               existing_nullable=False)
    op.drop_index(op.f('ix_usage_stats_feedback_score'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_sentiment'), table_name='usage_stats')
    op.drop_column('usage_stats', 'sentiment')
    op.drop_column('usage_stats', 'feedback_score')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('usage_stats', sa.Column('feedback_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage_stats', sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_usage_stats_sentiment'), 'usage_stats', ['sentiment'], unique=False)
    op.create_index(op.f('ix_usage_stats_feedback_score'), 'usage_stats', ['feedback_score'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               comment='Notification category or severity level',
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of creation',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_connectors_status'), 'connectors', ['status'], unique=False)
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.alter_column('connectors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('connectors', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('connectors', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_assistant_id_fkey'), 'chat_history', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assistants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('assistants', 'rerank_provider')
    # ### end Alembic commands ###
