"""Add avatar_url to users

Revision ID: 185c9a047467
Revises: f277630a13b0
Create Date: 2026-01-17 15:52:20.825583

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '185c9a047467'
down_revision: Union[str, Sequence[str], None] = 'f277630a13b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('chatstore:idx_key'), table_name='chatstore')
    # op.drop_table('chatstore')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.create_table('chatstore',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chatstore_pkey')),
    sa.UniqueConstraint('key', name=op.f('chatstore:unique_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('chatstore:idx_key'), 'chatstore', ['key'], unique=False)
    # ### end Alembic commands ###
