"""Add similarity_cutoff to assistants

Revision ID: 198405d6ca2e
Revises: 4fc82d033468
Create Date: 2026-01-07 14:17:20.850680

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '198405d6ca2e'
down_revision: Union[str, Sequence[str], None] = '4fc82d033468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('similarity_cutoff', sa.Float(), nullable=False, server_default='0.5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'similarity_cutoff')
    # ### end Alembic commands ###
