"""add_semantic_cache

Revision ID: 4f930e6075d5
Revises: bff3847a5c04
Create Date: 2026-01-13 08:16:33.068502

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f930e6075d5'
down_revision: Union[str, Sequence[str], None] = 'bff3847a5c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('use_semantic_cache', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('assistants', sa.Column('cache_similarity_threshold', sa.Float(), server_default=sa.text('0.90'), nullable=False))
    op.add_column('assistants', sa.Column('cache_ttl_seconds', sa.Integer(), server_default=sa.text('3600'), nullable=False))
    op.alter_column('assistants', 'avatar_text_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('assistants', 'reranker_provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('cohere', 'jina', 'local', name='rerankerprovider'),
               postgresql_using='reranker_provider::rerankerprovider',
               existing_nullable=True)
    op.alter_column('assistants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('assistants', 'reranker_provider',
               existing_type=sa.Enum('cohere', 'jina', 'local', name='rerankerprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('assistants', 'avatar_text_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('assistants', 'cache_ttl_seconds')
    op.drop_column('assistants', 'cache_similarity_threshold')
    op.drop_column('assistants', 'use_semantic_cache')
    # ### end Alembic commands ###
