"""add_cascade_delete

Revision ID: 4fc82d033468
Revises: 7527e66a3072
Create Date: 2026-01-06 08:54:22.834183

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fc82d033468'
down_revision: Union[str, Sequence[str], None] = '7527e66a3072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_assistant_connectors_connector_id'), 'assistant_connectors', type_='foreignkey')
    op.drop_constraint(op.f('fk_assistant_connectors_assistant_id'), 'assistant_connectors', type_='foreignkey')
    op.create_foreign_key(None, 'assistant_connectors', 'connectors', ['connector_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assistant_connectors', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('topic_stats_assistant_id_fkey'), 'topic_stats', type_='foreignkey')
    op.create_foreign_key(None, 'topic_stats', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usage_stats_assistant_id_fkey'), 'usage_stats', type_='foreignkey')
    op.create_foreign_key(None, 'usage_stats', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_stats', type_='foreignkey')
    op.create_foreign_key(op.f('usage_stats_assistant_id_fkey'), 'usage_stats', 'assistants', ['assistant_id'], ['id'])
    op.drop_constraint(None, 'topic_stats', type_='foreignkey')
    op.create_foreign_key(op.f('topic_stats_assistant_id_fkey'), 'topic_stats', 'assistants', ['assistant_id'], ['id'])
    op.drop_constraint(None, 'assistant_connectors', type_='foreignkey')
    op.drop_constraint(None, 'assistant_connectors', type_='foreignkey')
    op.create_foreign_key(op.f('fk_assistant_connectors_assistant_id'), 'assistant_connectors', 'assistants', ['assistant_id'], ['id'])
    op.create_foreign_key(op.f('fk_assistant_connectors_connector_id'), 'assistant_connectors', 'connectors', ['connector_id'], ['id'])
    # ### end Alembic commands ###
