"""Sync models with database

Revision ID: 58d6cc79c92d
Revises: 61ac41c83a99
Create Date: 2026-02-13 13:31:27.218239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d6cc79c92d'
down_revision: Union[str, Sequence[str], None] = '61ac41c83a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_history_assistant_id'), 'chat_history', ['assistant_id'], unique=False)
    op.drop_constraint(op.f('chat_history_assistant_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'assistants', ['assistant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('connectors', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('connectors', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_assistant_id_fkey'), 'chat_history', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_history_assistant_id'), table_name='chat_history')
    # ### end Alembic commands ###
