"""Add trending questions table

Revision ID: 6ccdb474f338
Revises: e38dc4593864
Create Date: 2026-01-01 10:22:26.185537

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ccdb474f338'
down_revision: Union[str, Sequence[str], None] = 'e38dc4593864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_stats',
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), server_default='1', nullable=False),
    sa.Column('raw_variations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_stats')
    # ### end Alembic commands ###
