"""add_user_id_to_notifications

Revision ID: 7527e66a3072
Revises: 79e451b98cf0
Create Date: 2026-01-06 08:11:03.924823

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7527e66a3072'
down_revision: Union[str, Sequence[str], None] = '79e451b98cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums first
    sa.Enum('GPT_4O', 'GPT_4O_MINI', 'GPT_4_TURBO', 'GPT_3_5_TURBO', 'GEMINI_1_5_PRO', 'GEMINI_1_5_FLASH', name='aimodel').create(op.get_bind())
    sa.Enum('COHERE', 'JINA', name='rerankerprovider').create(op.get_bind())
    sa.Enum('local_file', 'local_folder', name='connectortype').create(op.get_bind())
    sa.Enum('manual', 'cron', name='scheduletype').create(op.get_bind())

    op.execute("TRUNCATE TABLE notifications CASCADE")
    # Fix assistants data before altering columns
    op.execute("UPDATE assistants SET avatar_color = '#000000' WHERE avatar_color IS NULL")
    op.execute("UPDATE assistants SET avatar_text_color = '#FFFFFF' WHERE avatar_text_color IS NULL")
    op.execute("UPDATE assistants SET model = 'GPT_4O' WHERE model IS NULL") # Default to GPT_4O
    op.execute("UPDATE assistants SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE assistants SET updated_at = NOW() WHERE updated_at IS NULL")
    
    # Fix Assistants Enums (Model & Reranker)
    # Map legacy model inputs to strict Enum values
    op.execute("UPDATE assistants SET model = 'GEMINI_1_5_FLASH' WHERE model = 'gemini-1.5-flash'")
    op.execute("UPDATE assistants SET model = 'GEMINI_1_5_FLASH' WHERE model = 'Google Gemini'")
    op.execute("UPDATE assistants SET model = 'GEMINI_1_5_PRO' WHERE model = 'gemini-1.5-pro'")
    op.execute("UPDATE assistants SET model = 'GPT_4O' WHERE model = 'gpt-4o'")
    op.execute("UPDATE assistants SET model = 'GPT_4O_MINI' WHERE model = 'gpt-4o-mini'")
    op.execute("UPDATE assistants SET model = 'GPT_4_TURBO' WHERE model = 'gpt-4-turbo'")
    op.execute("UPDATE assistants SET model = 'GPT_3_5_TURBO' WHERE model = 'gpt-3.5-turbo'")
    
    # Uppercase others just in case
    op.execute("UPDATE assistants SET model = UPPER(REPLACE(model, '-', '_')) WHERE model NOT IN ('GPT_4O', 'GPT_4O_MINI', 'GPT_4_TURBO', 'GPT_3_5_TURBO', 'GEMINI_1_5_PRO', 'GEMINI_1_5_FLASH')")
    
    # Reranker normalization
    op.execute("UPDATE assistants SET reranker_provider = UPPER(reranker_provider)")

    # Fix Connectors data
    op.execute("UPDATE connectors SET schedule_cron = '0 0 * * *', schedule_type = 'cron' WHERE schedule_type = 'daily'")
    op.execute("UPDATE connectors SET schedule_cron = '0 0 * * 0', schedule_type = 'cron' WHERE schedule_type = 'weekly'")
    op.execute("UPDATE connectors SET schedule_cron = '0 0 1 * *', schedule_type = 'cron' WHERE schedule_type = 'monthly'")
    
    op.alter_column('assistants', 'avatar_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assistants', 'avatar_text_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assistants', 'model',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('GPT_4O', 'GPT_4O_MINI', 'GPT_4_TURBO', 'GPT_3_5_TURBO', 'GEMINI_1_5_PRO', 'GEMINI_1_5_FLASH', name='aimodel'),
               nullable=False,
               postgresql_using="model::aimodel")
    op.alter_column('assistants', 'reranker_provider',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('COHERE', 'JINA', name='rerankerprovider'),
               existing_nullable=True,
               postgresql_using="reranker_provider::rerankerprovider")
    op.alter_column('assistants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assistants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('connectors', 'connector_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('local_file', 'local_folder', name='connectortype'),
               nullable=True,
               postgresql_using="connector_type::connectortype")
    
    op.execute("ALTER TABLE connectors ALTER COLUMN schedule_type DROP DEFAULT")
    op.alter_column('connectors', 'schedule_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('manual', 'cron', name='scheduletype'),
               existing_nullable=True,
               existing_server_default=None, # Was 'manual'::varchar
               server_default=sa.text("'manual'"),
               postgresql_using="schedule_type::scheduletype")
    op.create_index(op.f('ix_error_logs_status_code'), 'error_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False)
    op.create_index('ix_error_logs_timestamp_status', 'error_logs', ['timestamp', 'status_code'], unique=False)
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_type', 'notifications', ['user_id', 'type'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('settings', 'value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index('ix_topic_stats_assistant_created', 'topic_stats', ['assistant_id', 'created_at'], unique=False)
    op.create_index('ix_topic_stats_assistant_frequency', 'topic_stats', ['assistant_id', 'frequency'], unique=False)
    op.create_index(op.f('ix_topic_stats_assistant_id'), 'topic_stats', ['assistant_id'], unique=False)
    op.create_index('ix_usage_stats_assistant_timestamp', 'usage_stats', ['assistant_id', 'timestamp'], unique=False)
    op.create_index('ix_usage_stats_feedback', 'usage_stats', ['assistant_id', 'feedback_score'], unique=False)
    op.create_index('ix_usage_stats_session', 'usage_stats', ['session_id', 'timestamp'], unique=False)
    op.create_index('ix_usage_stats_user_timestamp', 'usage_stats', ['user_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_usage_stats_user_timestamp', table_name='usage_stats')
    op.drop_index('ix_usage_stats_session', table_name='usage_stats')
    op.drop_index('ix_usage_stats_feedback', table_name='usage_stats')
    op.drop_index('ix_usage_stats_assistant_timestamp', table_name='usage_stats')
    op.drop_index(op.f('ix_topic_stats_assistant_id'), table_name='topic_stats')
    op.drop_index('ix_topic_stats_assistant_frequency', table_name='topic_stats')
    op.drop_index('ix_topic_stats_assistant_created', table_name='topic_stats')
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index('ix_notifications_user_type', table_name='notifications')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_column('notifications', 'user_id')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_index('ix_error_logs_timestamp_status', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_timestamp'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_status_code'), table_name='error_logs')
    op.alter_column('connectors', 'schedule_type',
               existing_type=sa.Enum('manual', 'cron', name='scheduletype'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('connectors', 'connector_type',
               existing_type=sa.Enum('local_file', 'local_folder', name='connectortype'),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assistants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('assistants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assistants', 'reranker_provider',
               existing_type=sa.Enum('COHERE', 'JINA', name='rerankerprovider'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('assistants', 'model',
               existing_type=sa.Enum('GPT_4O', 'GPT_4O_MINI', 'GPT_4_TURBO', 'GPT_3_5_TURBO', 'GEMINI_1_5_PRO', 'GEMINI_1_5_FLASH', name='aimodel'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assistants', 'avatar_text_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assistants', 'avatar_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
