"""Add avatar_vertical_position to users

Revision ID: 7d08b7230504
Revises: 185c9a047467
Create Date: 2026-01-17 16:08:22.031944

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d08b7230504'
"""Add avatar_vertical_position to users

Revision ID: 7d08b7230504
Revises: 185c9a047467
Create Date: 2026-01-17 16:08:22.031944

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d08b7230504'
down_revision: Union[str, Sequence[str], None] = '185c9a047467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable with default, then set to NOT NULL
    op.add_column('users', sa.Column('avatar_vertical_position', sa.Integer(), nullable=True, server_default='50'))
    op.execute('UPDATE users SET avatar_vertical_position = 50 WHERE avatar_vertical_position IS NULL')
    op.alter_column('users', 'avatar_vertical_position', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_vertical_position')
    # ### end Alembic commands ###
