"""add_token_usage_columns

Revision ID: 8719d6449a75
Revises: 6720795de228
Create Date: 2026-02-17 21:45:19.544615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8719d6449a75'
down_revision: Union[str, Sequence[str], None] = '6720795de228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('message_id', sa.Uuid(), nullable=True))
    op.add_column('usage_stats', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('usage_stats', sa.Column('is_cached', sa.Boolean(), nullable=False))
    op.add_column('usage_stats', sa.Column('cost', sa.Float(), nullable=False))
    op.create_index(op.f('ix_usage_stats_message_id'), 'usage_stats', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_stats_message_id'), table_name='usage_stats')
    op.drop_column('usage_stats', 'cost')
    op.drop_column('usage_stats', 'is_cached')
    op.drop_column('usage_stats', 'provider')
    op.drop_column('usage_stats', 'message_id')
    # ### end Alembic commands ###
