"""Add avatar_text_color to Assistant

Revision ID: 8b7e5cc71e70
Revises: dbc7d7e4b42d
Create Date: 2026-01-01 18:11:12.546242

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8b7e5cc71e70'
down_revision: Union[str, Sequence[str], None] = 'dbc7d7e4b42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('avatar_text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'avatar_text_color')
    # ### end Alembic commands ###
