"""remove_content_hash

Revision ID: 9042e2f5477e
Revises: a26e7251a5a4
Create Date: 2026-01-16 12:58:01.759592

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9042e2f5477e'
down_revision: Union[str, Sequence[str], None] = 'a26e7251a5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors_documents', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors_documents', sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
