"""Add user_authentication to Assistant

Revision ID: a2db2b18a9a2
Revises: 8b7e5cc71e70
Create Date: 2026-01-01 22:55:01.654423

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2db2b18a9a2'
down_revision: Union[str, Sequence[str], None] = '8b7e5cc71e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('user_authentication', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'user_authentication')
    # ### end Alembic commands ###
