"""add_avatar_vertical_position_to_assistants

Revision ID: b97a4bc14bb6
Revises: 4a2f1b8c9d0e
Create Date: 2026-01-10 17:08:15.687275

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b97a4bc14bb6'
down_revision: Union[str, Sequence[str], None] = '4a2f1b8c9d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('avatar_vertical_position', sa.Integer(), server_default=sa.text('50'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('assistants', 'reranker_provider',
               existing_type=sa.Enum('cohere', 'jina', 'local', name='rerankerprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('assistants', 'avatar_text_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('assistants', 'avatar_vertical_position')
    # ### end Alembic commands ###
