"""add_last_vectorized_at

Revision ID: ba8f33d34d4e
Revises: a01b02c03d04
Create Date: 2025-12-23 13:53:46.197731

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba8f33d34d4e'
down_revision: Union[str, Sequence[str], None] = 'a01b02c03d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors_documents', sa.Column('last_vectorized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors_documents', 'last_vectorized_at')
    # ### end Alembic commands ###
