"""add_connector_chunking_config

Revision ID: bff3847a5c04
Revises: 0aff30416f5d
Create Date: 2026-01-12 10:45:12.882788

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bff3847a5c04'
down_revision: Union[str, Sequence[str], None] = '0aff30416f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop columns if they exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('assistants')]
    
    if 'chunk_overlap' in columns:
        op.drop_column('assistants', 'chunk_overlap')
    if 'chunk_size' in columns:
        op.drop_column('assistants', 'chunk_size')
    op.add_column('connectors', sa.Column('chunk_size', sa.Integer(), server_default=sa.text('1024'), nullable=False))
    op.add_column('connectors', sa.Column('chunk_overlap', sa.Integer(), server_default=sa.text('200'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'chunk_overlap')
    op.drop_column('connectors', 'chunk_size')
    op.add_column('assistants', sa.Column('chunk_size', sa.INTEGER(), server_default=sa.text('1024'), autoincrement=False, nullable=False))
    op.add_column('assistants', sa.Column('chunk_overlap', sa.INTEGER(), server_default=sa.text('200'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
