"""add usage_stats

Revision ID: dbc7d7e4b42d
Revises: 6ccdb474f338
Create Date: 2026-01-01 14:39:31.227613

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbc7d7e4b42d'
down_revision: Union[str, Sequence[str], None] = '6ccdb474f338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_stats',
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=False),
    sa.Column('ttft', sa.Float(), nullable=True),
    sa.Column('step_duration_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_stats_assistant_id'), 'usage_stats', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_session_id'), 'usage_stats', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_timestamp'), 'usage_stats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_stats_user_id'), 'usage_stats', ['user_id'], unique=False)
    op.alter_column('connectors', 'last_sync_start_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('connectors', 'last_sync_end_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connectors', 'last_sync_end_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('connectors', 'last_sync_start_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_usage_stats_user_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_timestamp'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_session_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_assistant_id'), table_name='usage_stats')
    op.drop_table('usage_stats')
    # ### end Alembic commands ###
