"""add_reranker_fields_final

Revision ID: e38dc4593864
Revises: 03f2eef5eadd
Create Date: 2025-12-30 14:43:56.267128

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e38dc4593864'
down_revision: Union[str, Sequence[str], None] = '03f2eef5eadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('use_reranker', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('assistants', sa.Column('reranker_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assistants', sa.Column('top_k_retrieval', sa.Integer(), server_default=sa.text('25'), nullable=False))
    op.add_column('assistants', sa.Column('top_n_rerank', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'top_n_rerank')
    op.drop_column('assistants', 'top_k_retrieval')
    op.drop_column('assistants', 'reranker_provider')
    op.drop_column('assistants', 'use_reranker')
    # ### end Alembic commands ###
