"""add_retrieval_similarity_cutoff

Revision ID: f277630a13b0
Revises: 9042e2f5477e
Create Date: 2026-01-16 14:17:39.995452

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f277630a13b0'
down_revision: Union[str, Sequence[str], None] = '9042e2f5477e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('retrieval_similarity_cutoff', sa.Float(), server_default=sa.text('0.5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'retrieval_similarity_cutoff')
    # ### end Alembic commands ###
