"""add_user_id_to_chat_history

Revision ID: f9cb844ef13c
Revises: k6f7g8h9i0j1
Create Date: 2026-02-05 14:11:53.647306

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9cb844ef13c'
down_revision: Union[str, Sequence[str], None] = 'k6f7g8h9i0j1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_column('chat_history', 'user_id')
    # ### end Alembic commands ###
