"""remove_usage_stat_fields

Revision ID: g2b3c4d5e6f7
Revises: f1a2b3c4d5e6
Create Date: 2026-01-13 14:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'g2b3c4d5e6f7'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('ix_usage_stats_feedback', table_name='usage_stats')
    op.drop_column('usage_stats', 'feedback_score')
    op.drop_column('usage_stats', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('usage_stats', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('usage_stats', sa.Column('feedback_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_usage_stats_feedback', 'usage_stats', ['assistant_id', 'feedback_score'], unique=False)
    # ### end Alembic commands ###
